### ISSUE TITLE
NoDefClassFound AnimatorCompatHelper

### ISSUE THREAD

**Issue by CeccoCQ** [Yalantis/SearchFilter#12]
I'm with recyclerview-v7:26.1.0.

```
java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v4/animation/AnimatorCompatHelper;
                                                                                   at com.yalantis.filter.animator.FiltersListItemAnimator.resetAnimation(FiltersListItemAnimator.kt:427)
                                                                                   at com.yalantis.filter.animator.FiltersListItemAnimator.animateRemove(FiltersListItemAnimator.kt:136)
                                                                                   at android.support.v7.widget.SimpleItemAnimator.animateDisappearance(SimpleItemAnimator.java:109)
                                                                                   at android.support.v7.widget.RecyclerView.animateDisappearance(RecyclerView.java:3931)
                                                                                   at android.support.v7.widget.RecyclerView$4.processDisappeared(RecyclerView.java:523)
                                                                                   at android.support.v7.widget.ViewInfoStore.process(ViewInfoStore.java:242)
                                                                                   at android.support.v7.widget.RecyclerView.dispatchLayoutStep3(RecyclerView.java:3763)
                                                                                   at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3421)
                                                                                   at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3962)
                                                                                   at android.view.View.layout(View.java:19586)
                                                                                   at android.view.ViewGroup.layout(ViewGroup.java:6053)
                                                                                   at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                                                   at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                                                   at android.view.View.layout(View.java:19586)
                                                                                   at android.view.ViewGroup.layout(ViewGroup.java:6053)
```

**Comment by GauvainSeigneur** [comment]
Hi, I have the same issue, is due to Android version. Google has moved Android Support repo and some bug have come with it... 

A hotfix is to add this in your grade : 
```java
configurations.all {
    resolutionStrategy.eachDependency { DependencyResolveDetails details ->
        def requested = details.requested
        if (requested.group == 'com.android.support') {
            if (!requested.name.startsWith("multidex")) {
                details.useVersion '25.3.0'
            }
        }
    }
}
```

**Comment by CeccoCQ** [comment]
Hi @GauvainSeigneur ,
thanks for your response.

Did you find a solution that avoid the set of 25.3.0 version?
